global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    metrics_path: /metrics
    static_configs:
      - targets: ['185.241.195.151:8080']

  - job_name: 'system'
    static_configs:
      - targets: ['185.241.195.151:9100']


