definitions:
  store.Restaurant:
    properties:
      category:
        type: string
      commentsCount:
        type: integer
      deliveryPrice:
        type: integer
      deliveryTime:
        type: integer
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      rating:
        type: number
    type: object
  store.User:
    properties:
      birthday:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      phoneNumber:
        type: string
      username:
        type: string
    type: object
host: http://84.23.53.216:8001/
info:
  contact: {}
  license:
    name: Apache 2.0
  title: Prinesi-Poday API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: checking auth
      parameters:
      - description: Checking user authentication
        in: header
        name: cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success authenticate return id
          schema:
            type: integer
        "401":
          description: unauthorized
          schema: {}
      summary: checking auth
      tags:
      - Authorization
  /login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: Logining user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/store.User'
      produces:
      - application/json
      responses:
        "200":
          description: success login User return cookie
          schema:
            type: string
        "400":
          description: bad request
          schema: {}
        "404":
          description: not found
          schema: {}
        "500":
          description: internal server error
          schema: {}
      summary: Login user
      tags:
      - Authorization
  /logout:
    post:
      consumes:
      - application/json
      description: Log out user
      parameters:
      - description: Log out user
        in: header
        name: cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: success log out
        "400":
          description: bad request
          schema: {}
        "401":
          description: unauthorized
          schema: {}
      summary: Log out user
      tags:
      - Authorization
  /restaurants:
    get:
      consumes:
      - application/json
      description: giving array of restaurants
      produces:
      - application/json
      responses:
        "200":
          description: success returning array of restaurants
          schema:
            items:
              $ref: '#/definitions/store.Restaurant'
            type: array
        "500":
          description: internal server error
          schema: {}
      summary: giving restaurats
      tags:
      - Restaurants
  /users:
    get:
      consumes:
      - application/json
      description: Signing up a user
      parameters:
      - description: User object for signing up
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/store.User'
      produces:
      - application/json
      responses:
        "200":
          description: success create User return id
          schema:
            type: integer
        "400":
          description: bad request
          schema: {}
        "500":
          description: internal server error
          schema: {}
      summary: Signing up a user
      tags:
      - User
swagger: "2.0"
