definitions:
  store.User:
    properties:
      birthday:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      phoneNumber:
        type: string
      username:
        type: string
    type: object
host: http://84.23.53.216:8001/
info:
  contact: {}
  license:
    name: Apache 2.0
  title: Prinesi-Poday API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: checking auth
      parameters:
      - description: Checking user authentication
        in: header
        name: cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success authenticate return id
          schema:
            type: integer
        "401":
          description: unauthorized
          schema: {}
      summary: checking auth
      tags:
      - Authorization
  /logout:
    post:
      consumes:
      - application/json
      description: Log out user
      parameters:
      - description: Log out user
        in: header
        name: cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: success log out
        "400":
          description: bad request
          schema: {}
        "401":
          description: unauthorized
          schema: {}
      summary: Log out user
      tags:
      - Authorization
  /users:
    post:
      consumes:
      - application/json
      description: Signing up a user
      parameters:
      - description: User object for signing up
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/store.User'
      produces:
      - application/json
      responses:
        "200":
          description: success create User return id
          schema:
            type: integer
        "400":
          description: bad request
          schema: {}
        "500":
          description: internal server error
          schema: {}
      summary: Signing up a user
      tags:
      - User
swagger: "2.0"
